/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    destinations: Destination;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Solo un admin crea usuarios y cambia roles. Cada uno puede editar su nombre y su contraseña.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Solo un admin puede cambiar el rol. Un agente no se lo cambia a sí mismo.
   */
  role: 'admin' | 'encargado' | 'agente';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Si viene del sitio estático, p. ej. /destinos/salta.png. El render la prefiere sobre la URL del archivo.
   */
  legacyPath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Borrador: no se ve en el sitio. Publicado: se ve en la web. Un agente publica directo solo salidas, precios y vigencia; el resto queda en borrador para un encargado.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  slug: string;
  /**
   * Empates de la home y el orden de /destinos. No reordenar sin motivo.
   */
  sortOrder: number;
  /**
   * Se completa sola cada vez que alguien guarda. No se edita a mano.
   */
  lastReviewedAt?: string | null;
  /**
   * Quien guardó la ficha por última vez. Tampoco se edita a mano.
   */
  reviewedBy?: (number | null) | User;
  /**
   * Se marca sola cuando un agente guarda un borrador. Un encargado o un admin la baja al publicar.
   */
  pendingApproval?: boolean | null;
  name: string;
  country: string;
  region: 'nacional' | 'internacional';
  heroImage: number | Media;
  flyerImage?: (number | null) | Media;
  description: string;
  metaTitle: string;
  metaDescription: string;
  /**
   * Si queda vacío, la ficha usa “Paquetes a {nombre}”.
   */
  h1?: string | null;
  priceFrom?: number | null;
  currency: 'ARS' | 'USD';
  priceNote?: string | null;
  /**
   * Obligatorio al publicar si hay un precio. El día indicado sigue vigente. Si se pasa, el sitio no muestra el monto y dice «Consultá precio actualizado».
   */
  priceValidUntil?: string | null;
  departures?:
    | {
        /**
         * Fecha real en AAAA-MM-DD, por ejemplo 2026-07-08. Una salida nueva o que modifiques no puede ser de un día que ya pasó.
         */
        date: string;
        /**
         * Cómo la lee el pasajero, por ejemplo «8 de Julio».
         */
        displayDate: string;
        priceFrom?: number | null;
        currency?: ('ARS' | 'USD') | null;
        /**
         * Confirmada: hay lugar. Últimos lugares: queda poco. Agotada: no se ofrece. Consultar: hay que chequear el cupo.
         */
        status: 'confirmed' | 'few-seats' | 'sold-out' | 'inquire';
        transport: 'aereo' | 'bus' | 'bus-cama' | 'mix';
        nights: number;
        note?: string | null;
        program?: string | null;
        stayLabel?: string | null;
        /**
         * El monto es final, no una tarifa “desde”.
         */
        priceIsFinal?: boolean | null;
        /**
         * Vigencia propia de esta salida. Si la dejás vacía, usa la del destino. Si vence, esta salida no muestra el monto.
         */
        priceValidUntil?: string | null;
        id?: string | null;
      }[]
    | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  typicalInclusions?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  optionalExcursions?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  travelTip?: string | null;
  faq?:
    | {
        /**
         * Id estable, p. ej. iguazu-incluye.
         */
        faqId: string;
        question: string;
        answer?:
          | (
              | {
                  value: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'text';
                }
              | {
                  label: string;
                  href: string;
                  external?: boolean | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'link';
                }
              | {
                  /**
                   * La URL se arma al publicar con el nombre del destino y el teléfono de la agencia.
                   */
                  label: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'whatsapp';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  legacyPath?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  slug?: T;
  sortOrder?: T;
  lastReviewedAt?: T;
  reviewedBy?: T;
  pendingApproval?: T;
  name?: T;
  country?: T;
  region?: T;
  heroImage?: T;
  flyerImage?: T;
  description?: T;
  metaTitle?: T;
  metaDescription?: T;
  h1?: T;
  priceFrom?: T;
  currency?: T;
  priceNote?: T;
  priceValidUntil?: T;
  departures?:
    | T
    | {
        date?: T;
        displayDate?: T;
        priceFrom?: T;
        currency?: T;
        status?: T;
        transport?: T;
        nights?: T;
        note?: T;
        program?: T;
        stayLabel?: T;
        priceIsFinal?: T;
        priceValidUntil?: T;
        id?: T;
      };
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  typicalInclusions?:
    | T
    | {
        text?: T;
        id?: T;
      };
  optionalExcursions?:
    | T
    | {
        text?: T;
        id?: T;
      };
  travelTip?: T;
  faq?:
    | T
    | {
        faqId?: T;
        question?: T;
        answer?:
          | T
          | {
              text?:
                | T
                | {
                    value?: T;
                    id?: T;
                    blockName?: T;
                  };
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                    id?: T;
                    blockName?: T;
                  };
              whatsapp?:
                | T
                | {
                    label?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}